--관리자

/* 테이블 드랍 */
DROP TABLE ADMIN CASCADE CONSTRAINTS;   --관리자
DROP TABLE ADMINPAGE CASCADE CONSTRAINTS;    --페이지 관리
DROP TABLE NOTICE CASCADE CONSTRAINTS;    --공지사항
DROP TABLE FAQ CASCADE CONSTRAINTS;    --FAQ
DROP TABLE SENDMSG CASCADE CONSTRAINTS;    --보낸쪽지
DROP TABLE RECEIVEMSG CASCADE CONSTRAINTS;    --받은쪽지

/* 시퀀스 드랍 */
DROP SEQUENCE ADMINPAGE_SEQ;
DROP SEQUENCE NOTICE_SEQ;
DROP SEQUENCE FAQ_SEQ;
DROP SEQUENCE SENDMSG_SEQ;
DROP SEQUENCE RECEIVEMSG_SEQ;

/* 시퀀스 생성 */
CREATE SEQUENCE ADMINPAGE_SEQ START WITH 1 INCREMENT BY 1;    --페이지 관리
CREATE SEQUENCE NOTICE_SEQ START WITH 1 INCREMENT BY 1;    --공지사항
CREATE SEQUENCE FAQ_SEQ START WITH 1 INCREMENT BY 1;    --FAQ
CREATE SEQUENCE SENDMSG_SEQ START WITH 1 INCREMENT BY 1;    --보낸쪽지
CREATE SEQUENCE RECEIVEMSG_SEQ START WITH 1 INCREMENT BY 1;    --받은쪽지

/* 테이블 생성 */
/* 관리자 테이블 */
CREATE TABLE ADMIN (
	ADMINID VARCHAR2(50) PRIMARY KEY, /* 관리자ID */
	ADMINNAME VARCHAR2(20) NOT NULL, /* 관리자이름 */
	PWD VARCHAR2(30) NOT NULL, /* 비밀번호 */
	REGDATE DATE DEFAULT SYSDATE /* 가입일 */
);

/* 페이지관리 테이블 */
CREATE TABLE ADMINPAGE (
	PAGENO NUMBER(10) PRIMARY KEY, /* 페이지번호 */
	ADMINID VARCHAR2(50), /* 관리자ID */
	PAGENAME VARCHAR2(50), /* 페이지이름 */
	PAGECONTENT CLOB, /* 페이지내용 */
	PAGEIMAGE VARCHAR2(50) /* 페이지이미지 */
);

ALTER TABLE ADMINPAGE
	ADD
		CONSTRAINT FK_ADMIN_TO_ADMINPAGE
		FOREIGN KEY (
			ADMINID
		)
		REFERENCES ADMIN (
			ADMINID
		);

/* 공지사항 테이블 */
CREATE TABLE NOTICE (
	NNO NUMBER(10) PRIMARY KEY, /* 공지사항글번호 */
	ADMINID VARCHAR2(50) NOT NULL, /* 관리자ID */
	NTITLE VARCHAR2(200) NOT NULL, /* 공지사항제목 */
	NCONTENT CLOB NOT NULL, /* 공지사항내용 */
	REGDATE DATE DEFAULT SYSDATE, /* 글등록일 */
	DELFLAG CHAR(1) DEFAULT 'N' /* 삭제여부 */
);

ALTER TABLE NOTICE
	ADD
		CONSTRAINT FK_ADMIN_TO_NOTICE
		FOREIGN KEY (
			ADMINID
		)
		REFERENCES ADMIN (
			ADMINID
		);

/* FAQ 테이블 */
CREATE TABLE FAQ (
	FAQNO NUMBER(10) PRIMARY KEY, /* FAQ번호 */
	ADMINID VARCHAR2(50), /* 관리자ID */
	CATEGORY VARCHAR2(50) NOT NULL, /* 카테고리명 */
	FAQTITLE VARCHAR2(200) NOT NULL, /* FAQ제목 */
	FAQCONTENT CLOB NOT NULL, /* FAQ내용 */
	FAQREGDATE DATE DEFAULT SYSDATE, /* FAQ등록일 */
	DELFLAG CHAR(1) DEFAULT 'N' /* 삭제여부 */
);

ALTER TABLE FAQ
	ADD
		CONSTRAINT FK_ADMIN_TO_FAQ
		FOREIGN KEY (
			ADMINID
		)
		REFERENCES ADMIN (
			ADMINID
		);

/* 보낸쪽지 */
CREATE TABLE SENDMSG (
	SMSGNO NUMBER(10) PRIMARY KEY, /* 보낸쪽지번호 */
	SENDER VARCHAR2(50) NOT NULL, /* 보내는사람 */
	TITLE VARCHAR2(50) NOT NULL, /* 쪽지제목 */
	CONTENT VARCHAR2(3000) NOT NULL, /* 쪽지내용 */
	SDELFLAG CHAR(1) DEFAULT 'N', /* 보낸쪽지삭제여부 */
	REGDATE DATE DEFAULT SYSDATE, /* 보낸날짜 */
	CODE CHAR(1) /* 사용자구분코드 */
);

/* 받은쪽지 */


/* 받은쪽지 */
CREATE TABLE RECEIVEMSG (
	RMSGNO NUMBER(10) NOT NULL, /* 받은쪽지번호 */
	SMSGNO NUMBER(10) NOT NULL, /* 보낸쪽지번호 */
	RECIPIENT VARCHAR2(50) NOT NULL, /* 받는사람 */
	RDELFLAG CHAR(1) DEFAULT 'N', /* 받은쪽지삭제여부 */
	READFLAG CHAR(1) DEFAULT 'N' /* 읽음표시 */
);

ALTER TABLE RECEIVEMSG
	ADD
		CONSTRAINT RECEIVEMSG
		PRIMARY KEY (
			RMSGNO
		);

ALTER TABLE RECEIVEMSG
	ADD
		CONSTRAINT FK_SENDMSG_TO_RECEIVEMSG
		FOREIGN KEY (
			SMSGNO
		)
		REFERENCES SENDMSG (
			SMSGNO
		);

